### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by hariharan-uno**
Sorry this is a rather lengthy PR. I was bored, so I started cleaning up the code a little bit.
Important bits:
- Handle errors using return values
- Remove NewSidebar and add initSidebar method on *Game
- Unexport `Sidebar`, `ByScore` types
- change `log` to `logf` so that it is similar to the std library

I changed things mostly to follow conventions of idiomatic go. Please check the diffs and comment if you find any errors or doubts.

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks :) Re: `logf` is http://golang.org/src/net/http/server.go#L1771 what you mean? I'm guessing the `f` is added to differentiate it from the `log` package?

**Comment by hariharan-uno** [comment]
i just added `f` to indicate that it takes a format string as the first arg. Similar to `fmt.Print`, `fmt.Printf`.

**Comment by jpillora** [comment]
Ahhh right

**Comment by jpillora** [comment]
One more question, is [adding a `Game` method `initSidebar` in the `sidebar.go` file](https://github.com/jpillora/ssh-tron/blob/master/tron/sidebar.go#L21-L29) idiomatic Go?

**Comment by hariharan-uno** [comment]
Oh..I think it should be in `game.go`. Missed it!

**Comment by jpillora** [comment]
Inlined https://github.com/jpillora/ssh-tron/commit/a6de7631b49273bf2ca0bcc2708b0a9e2598ae63

**Pull request merged**
